 bi:
  outputs:
    dev:
      account: RZIRXYJ-RY81273
      database: lightdash_db
      password: Salma27med313!
      schema: bi
      threads: 10
      type: snowflake
      user: salma
      warehouse: compute_wh
  target: dev
